/**
 * generate-catalog.mjs
 * --------------------
 * Scans public/models and writes src/build/catalog.generated.ts — the list of
 * every placeable asset, grouped into the categories the build-mode palette
 * shows. Run it after adding or removing GLBs:
 *
 *     node scripts/generate-catalog.mjs
 *
 * Nothing else generates code in this project; the output is committed so the
 * build never depends on this script having been run.
 */

import { readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MODELS = join(ROOT, 'public/models');

/** camelCase / kebab-case / snake_case → "Title Case Words". */
function label(name) {
  return name
    .replace(/[-_]+/g, ' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * Ordered rules: the first matching pattern wins, so `kitchenCabinetUpper`
 * lands in Kitchen rather than Storage. `null` means "don't offer this asset"
 * — used for the shell pieces HouseShell places itself.
 */
const FURNITURE_RULES = [
  [/^(wall|floor|doorway|stairs|paneling)/i, 'Structure'],
  [/^(kitchen|hood|toaster)/i, 'Kitchen'],
  [/^(bathroom|bathtub|shower|toilet|washer|dryer)/i, 'Bathroom'],
  [/^(bed|cabinetBed)/i, 'Bedroom'],
  [/^(chair|stool|bench|lounge|pillow)/i, 'Seating'],
  [/^(table|desk|sideTable)/i, 'Tables'],
  [/^(bookcase|cabinet|coatRack|cardboardBox)/i, 'Storage'],
  [/^(lamp|ceilingFan)/i, 'Lighting'],
  [/^(computer|laptop|television|radio|speaker)/i, 'Electronics'],
  [/^(plant|potted|books|bear|rug|trashcan)/i, 'Decor'],
];

const ARCADE_STRUCTURE = /^(wall|floor|column)/i;

function glbs(dir) {
  return readdirSync(join(MODELS, dir))
    .filter((f) => f.endsWith('.glb'))
    .sort();
}

/** kind: how the object behaves once placed — see src/build/types.ts. */
const entries = [];
const push = (dir, file, category, kind = 'prop', extra = {}) =>
  entries.push({
    url: `/models/${dir}/${file}`,
    name: label(file.replace(/\.glb$/, '')),
    category,
    kind,
    ...extra,
  });

// ── Furniture kit ──────────────────────────────────────────────────────────
for (const file of glbs('furniture')) {
  const base = file.replace(/\.glb$/, '');
  const rule = FURNITURE_RULES.find(([re]) => re.test(base));
  push('furniture', file, rule ? rule[1] : 'Decor');
}

// ── Arcade kit: cabinets are playable kiosks, the rest is dressing ─────────
for (const file of glbs('arcade')) {
  const base = file.replace(/\.glb$/, '');
  if (base.startsWith('character-')) continue; // handled with the characters
  push('arcade', file, ARCADE_STRUCTURE.test(base) ? 'Structure' : 'Arcade');
}

// ── Outdoor kits ───────────────────────────────────────────────────────────
for (const file of glbs('city')) push('city', file, 'City');
for (const file of glbs('road')) push('road', file, 'Street');
for (const file of glbs('station')) push('station', file, 'Space Station');

// ── Characters ─────────────────────────────────────────────────────────────
for (const file of glbs('npc')) push('npc', file, 'People', 'npc');
for (const file of glbs('arcade')) {
  if (file.startsWith('character-')) push('arcade', file, 'People', 'npc');
}
for (const file of glbs('animals')) {
  const species = file.replace(/^animal-/, '').replace(/\.glb$/, '');
  push('animals', file, 'Animals', 'animal', { species });
}

const CATEGORY_ORDER = [
  'Seating',
  'Tables',
  'Storage',
  'Kitchen',
  'Bedroom',
  'Bathroom',
  'Lighting',
  'Electronics',
  'Decor',
  'Arcade',
  'People',
  'Animals',
  'City',
  'Street',
  'Space Station',
  'Structure',
];

entries.sort(
  (a, b) =>
    CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category) ||
    a.name.localeCompare(b.name),
);

const body = entries
  .map((e) => `  ${JSON.stringify(e)},`)
  .join('\n');

const out = `/**
 * catalog.generated.ts
 * --------------------
 * GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
 * Every asset build mode can place, grouped for the palette.
 */

import type { CatalogEntry } from './types';

export const CATEGORY_ORDER = ${JSON.stringify(CATEGORY_ORDER, null, 2).replace(/\n/g, '\n')} as const;

export const CATALOG: CatalogEntry[] = [
${body}
];
`;

mkdirSync(join(ROOT, 'src/build'), { recursive: true });
writeFileSync(join(ROOT, 'src/build/catalog.generated.ts'), out);
console.log(`Wrote ${entries.length} catalog entries.`);
